### Criar um novo usuário


POST http://localhost:8080/users 
Content-Type: application/json

{
    "name": "João Victor",
    "email": "joao@example.com",
    "login": "joaovictor",
    "password": "123456",
    "address": "Rua Exemplo, 123"
}

### Listar todos os usuários


GET http://localhost:8080/users

### Buscar usuário por ID

GET http://localhost:8080/users/1

### Atualizar usuário

PUT http://localhost:8080/users/1 
Content-Type: application/json

{
    "name": "João Atualizado",
    "email": "joao_atualizado@example.com",
    "login": "joaovictor",
    "password": "novaSenha",
    "address": "Rua Nova, 456"
}

### Deletar usuário por ID

DELETE http://localhost:8080/users/1